# Generated by Django 5.1.4 on 2026-08-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villa",
            name="bedrooms",
        ),
        migrations.AddField(
            model_name="villa",
            name="bathroom_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="villa",
            name="building_area",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="villa",
            name="construction_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="villa",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="villa",
            name="land_area",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="villa",
            name="parking_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="villa",
            name="room_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
