# Generated by Django 5.1.4 on 2026-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0002_remove_villa_bedrooms_villa_bathroom_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villa",
            name="features",
        ),
        migrations.AddField(
            model_name="villa",
            name="caretaker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="villa",
            name="deed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="villa",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="villa",
            name="pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="villa",
            name="roof",
            field=models.BooleanField(default=False),
        ),
    ]
