# Generated by Django 5.1.4 on 2026-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0003_remove_villa_features_villa_caretaker_villa_deed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villa",
            name="address",
        ),
        migrations.AddField(
            model_name="villa",
            name="location",
            field=models.CharField(
                choices=[
                    ("soheiliyeh", "سهیلیه"),
                    ("kordan", "کردان"),
                    ("aghcheh-hesar", "آغچه\u200cحصار"),
                    ("zakiabad", "زکی\u200cآباد"),
                ],
                db_index=True,
                default="soheiliyeh",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
