# Generated by Django 5.1.4 on 2026-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0005_earth_earthimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="earth",
            name="has_utilities",
            field=models.BooleanField(default=False),
        ),
    ]
