# Generated by Django 5.1.4 on 2026-08-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0006_earth_has_utilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("soheiliyeh", "سهیلیه"),
                            ("kordan", "کردان"),
                            ("aghcheh-hesar", "آغچه\u200cحصار"),
                            ("zakiabad", "زکی\u200cآباد"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("poster", models.ImageField(upload_to="gardens/")),
                ("land_area", models.PositiveIntegerField(blank=True, null=True)),
                ("deed", models.BooleanField(default=False)),
                ("caretaker", models.BooleanField(default=False)),
                ("in_urban_area", models.BooleanField(default=False)),
                ("has_utilities", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GardenImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gardens/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="villas.garden",
                    ),
                ),
            ],
        ),
    ]
