# Generated by Django 5.1.4 on 2026-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0007_garden_gardenimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="villa",
            name="ip_pin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="villa",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
