# Generated by Django 5.1.4 on 2026-08-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0008_villa_ip_pin_villa_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="villa",
            old_name="ip_pin",
            new_name="is_pin",
        ),
    ]
