# Generated by Django 5.1.4 on 2026-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0009_rename_ip_pin_villa_is_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="earth",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
