# Generated by Django 5.1.4 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villas", "0010_earth_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="garden",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
